[settings]
# --- 1. 動作モード設定 ---
# Trueにするとモデルの学習を毎回実行します。Falseにすると、設定が一致すれば保存済みのハイパーパラメータを読み込みます。
PERFORM_TRAINING = True

# --- 2. モデルと学習データ、最適化の設定 ---
mat_name = 50A470
target_freq = 20
kernel_type = Matern52

# 学習に使用する磁束密度の振幅範囲 (T)
Bmtrain_min = 0.1
Bmtrain_max = 1.8
train_step = 0.1

# Akimaデータを学習データとして使用するかどうか (True/False)
USE_AKIMA_DATA = True

OPTIMIZER = lbfgsb
MAX_ITERS = 1000
NUM_RESTARTS = 10

# --- 3. 回帰（予測）対象の設定 ---
Bmreg_min = 0.05
Bmreg_max = 1.8
step = 0.05