; ==============================================================================
; ニューラルネットワーク回帰 (1. NN.py) の設定ファイル
; ==============================================================================

[settings]
; Trueにするとモデルの学習から実行。Falseにすると学習済みモデルを読み込む
PERFORM_TRAINING = True
mat_name = 50A470
target_freq = 20

[architecture]
; 隠れ層のノード数をカンマ区切りで指定。例: 1024,512
HIDDEN_LAYERS = 20000
; 活性化関数を指定。サポート: ReLU, Tanh, Sigmoid
ACTIVATION_FUNC = ReLU

[training]
LEARNING_RATE = 0.0002
EPOCHS = 100000
BATCH_SIZE = 32
GRAD_CLIP = 1.0
; 損失関数を指定。サポート: MSE, RMSE
LOSS_FUNC = MSE

[data]
; 学習データの磁束密度振幅(Bm)の範囲とステップ
Bmtrain_min = 0.1
Bmtrain_max = 1.8
train_step = 0.1

[regression]
; 回帰（予測）対象の磁束密度振幅(Bm)の範囲とステップ
Bmreg_min = 0.05
Bmreg_max = 1.8
step = 0.05